
namespace GoldAddin
{
	/// <summary>
	/// Gold compiler message.
	/// </summary>
    public class CompilerMessage
    {
		string text;
		MessageSeverity severity;
		string fileName;
		int line;
		int column;
		string rawText;

		/// <summary>
		/// Initializes a new instance of the <see cref="GoldAddin.CompilerMessage"/> class.
		/// </summary>
		public CompilerMessage(MessageSeverity severity, string text,
		                           string fileName, int line, int column)
		{
			this.severity = severity;
			this.text = text;
			this.fileName = fileName;
			this.line = line;
			this.column = column;
			rawText = string.Empty;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="GoldAddin.CompilerMessage"/> class.
		/// </summary>
		public CompilerMessage(MessageSeverity severity, string text, string fileName, int line,
		                       int column, string rawText)
		{
			this.severity = severity;
			this.text = text;
			this.fileName = fileName;
			this.line = line;
			this.column = column;
			this.rawText = rawText;
		}


		/// <summary>
		/// Gets the message text
		/// </summary>
        public string Text
        { get { return text; } }

		/// <summary>
		/// Gets the severity of the compiler message
		/// </summary>
        public MessageSeverity Severity
        { get { return severity; } }
		        
		/// <summary>
		/// Gets the name of the file being compiled
		/// </summary>
        public string File
        { get { return fileName; } }

		/// <summary>
		/// Gets the line number that pertains to this compiler message
		/// </summary>
        public int Line
        { get { return line; } }

		/// <summary>
		/// Gets the column number that pertains to this compiler message
		/// </summary>
        public int Column
        { get { return column; } }

		/// <summary>
		/// Gets the complete text generated by the compiler for 
		/// the associated message
		/// </summary>
		public string RawText
		{ get { return rawText; } }

    }


	public enum MessageSeverity
	{
		Info, Warning, Error, Success  
	}
}
